
HTTP_500_INTERNAL_SERVER_ERROR = "服务器内部错误"
HTTP_422_UNPROCESSABLE_ENTITY = "请求参数错误"
HTTP_403_FORBIDDEN = "权限被拒绝"
HTTP_404_NOT_FOUND = "资源未找到"
HTTP_400_BAD_REQUEST = "错误请求"
HTTP_401_UNAUTHORIZED = "用户未认证"


DATABASE_600_BAD_SQL = "数据库错误"
DATABASE_610_NOT_FOUND = "数据不存在"
